### ISSUE TITLE
[Feature Request] Faucet Response

### ISSUE THREAD

**Issue by 0xPrimata** [aptos-labs/aptos-python-sdk#15]
# 🚀 Feature Request Description

It would be great if the faucet had a proper response on successful fund_account() requests. Currently it returns `None` and it ends up being an unclear response. A hash of the transaction could be a lot better as its already included in the response but it's not returned:

https://github.com/aptos-labs/aptos-python-sdk/blob/e5e1ecb0a6bea419a24098f17582798cdfc7be56/aptos_sdk/async_client.py#L959

## Motivation

Improve development experience.

**Comment by banool** [comment]
Good request, we should return the txn hashes. We should also add a flag like `wait_for_txns` (`True` by default) so the user can opt out of having the SDK wait on the caller's behalf for the txns.
